
package au.net.electronichealth.ns.mhr.svc.registermhr._2;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "registerPCEHRService", targetNamespace = "http://ns.electronichealth.net.au/pcehr/svc/RegisterPCEHR/2.0", wsdlLocation = "wsdl/B2B_RegisterMHR.wsdl")
public class RegisterMHRService
    extends Service
{

    private final static URL REGISTERMHRSERVICE_WSDL_LOCATION;
    private final static WebServiceException REGISTERMHRSERVICE_EXCEPTION;
    private final static QName REGISTERMHRSERVICE_QNAME = new QName("http://ns.electronichealth.net.au/pcehr/svc/RegisterPCEHR/2.0", "registerPCEHRService");

    static {
        REGISTERMHRSERVICE_WSDL_LOCATION = au.net.electronichealth.ns.mhr.svc.registermhr._2.RegisterMHRService.class.getResource("wsdl/B2B_RegisterMHR.wsdl");
        WebServiceException e = null;
        if (REGISTERMHRSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'wsdl/B2B_RegisterMHR.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        REGISTERMHRSERVICE_EXCEPTION = e;
    }

    public RegisterMHRService() {
        super(__getWsdlLocation(), REGISTERMHRSERVICE_QNAME);
    }

    public RegisterMHRService(WebServiceFeature... features) {
        super(__getWsdlLocation(), REGISTERMHRSERVICE_QNAME, features);
    }

    public RegisterMHRService(URL wsdlLocation) {
        super(wsdlLocation, REGISTERMHRSERVICE_QNAME);
    }

    public RegisterMHRService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REGISTERMHRSERVICE_QNAME, features);
    }

    public RegisterMHRService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegisterMHRService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return the result
     *     returns RegisterMHRPortType
     */
    @WebEndpoint(name = "registerPCEHRSOAP12Port")
    public RegisterMHRPortType getRegisterMHRSOAP12Port() {
        return super.getPort(new QName("http://ns.electronichealth.net.au/pcehr/svc/RegisterPCEHR/2.0", "registerPCEHRSOAP12Port"), RegisterMHRPortType.class);
    }

    /**
     * 
     * @param features web service features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return the result
     *     returns RegisterMHRPortType
     */
    @WebEndpoint(name = "registerPCEHRSOAP12Port")
    public RegisterMHRPortType getRegisterMHRSOAP12Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://ns.electronichealth.net.au/pcehr/svc/RegisterPCEHR/2.0", "registerPCEHRSOAP12Port"), RegisterMHRPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REGISTERMHRSERVICE_EXCEPTION!= null) {
            throw REGISTERMHRSERVICE_EXCEPTION;
        }
        return REGISTERMHRSERVICE_WSDL_LOCATION;
    }

}
