
package au.net.electronichealth.ns.mhr.b2b.svc.mhrprofile._1;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PCEHRProfileService", targetNamespace = "http://ns.electronichealth.net.au/pcehr/b2b/svc/PCEHRProfile/1.1", wsdlLocation = "wsdl/B2B_MHRProfile.wsdl")
public class MHRProfileService
    extends Service
{

    private final static URL PCEHRPROFILESERVICE_WSDL_LOCATION;
    private final static WebServiceException PCEHRPROFILESERVICE_EXCEPTION;
    private final static QName PCEHRPROFILESERVICE_QNAME = new QName("http://ns.electronichealth.net.au/pcehr/b2b/svc/PCEHRProfile/1.1", "PCEHRProfileService");

    static {
        PCEHRPROFILESERVICE_WSDL_LOCATION = au.net.electronichealth.ns.mhr.b2b.svc.mhrprofile._1.MHRProfileService.class.getResource("wsdl/B2B_MHRProfile.wsdl");
        WebServiceException e = null;
        if (PCEHRPROFILESERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'wsdl/B2B_MHRProfile.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        PCEHRPROFILESERVICE_EXCEPTION = e;
    }

    public MHRProfileService() {
        super(__getWsdlLocation(), PCEHRPROFILESERVICE_QNAME);
    }

    public MHRProfileService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PCEHRPROFILESERVICE_QNAME, features);
    }

    public MHRProfileService(URL wsdlLocation) {
        super(wsdlLocation, PCEHRPROFILESERVICE_QNAME);
    }

    public MHRProfileService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PCEHRPROFILESERVICE_QNAME, features);
    }

    public MHRProfileService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MHRProfileService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return the result
     *     returns MHRProfilePortType
     */
    @WebEndpoint(name = "PCEHRProfileSOAP12Port")
    public MHRProfilePortType getPCEHRProfileSOAP12Port() {
        return super.getPort(new QName("http://ns.electronichealth.net.au/pcehr/b2b/svc/PCEHRProfile/1.1", "PCEHRProfileSOAP12Port"), MHRProfilePortType.class);
    }

    /**
     * 
     * @param features web service features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return the result
     *     returns MHRProfilePortType
     */
    @WebEndpoint(name = "PCEHRProfileSOAP12Port")
    public MHRProfilePortType getPCEHRProfileSOAP12Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://ns.electronichealth.net.au/pcehr/b2b/svc/PCEHRProfile/1.1", "PCEHRProfileSOAP12Port"), MHRProfilePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PCEHRPROFILESERVICE_EXCEPTION!= null) {
            throw PCEHRPROFILESERVICE_EXCEPTION;
        }
        return PCEHRPROFILESERVICE_WSDL_LOCATION;
    }

}
